Travis/OSX: Add debug lsof -n -i | grep LISTEN, more debug
because it seems that gRPC daemon does not work ...
Error: Get http://127.0.0.1:2017/page_grpc_printdebug.html: dial
tcp 127.0.0.1:2017: getsockopt: connection reset by peer